# Generated by Django 3.0.3 on 2020-03-03 13:53

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField(blank='True', null='True', verbose_name='video')),
                ('name_audio', models.CharField(blank='True', max_length=50, null='True')),
                ('audio', models.FileField(blank='True', default='', null='True', upload_to='files/')),
                ('image', models.ImageField(default='', upload_to='image/', verbose_name='Изображение')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
