# Generated by Django 3.0.4 on 2020-03-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainpage',
            managers=[
            ],
        ),
    ]
