# Generated by Django 3.0.4 on 2020-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
